on:
  push:
    branches:
      - '**'

jobs:
  secret-search-job:
    runs-on: 'ubuntu-latest'
    name: Job to scan for secrets
    steps:
      - name: Download and install secret-search
        run: |
          pip install secret-search
          
      - name: Execute secret-search
        run: |
          secret-search
